// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

/**
 * Sichere Channel-Subscription die in Firefox nicht crasht.
 * Firefox blockiert WebSocket in bestimmten Kontexten ("The operation is insecure").
 * Diese Wrapper-Funktion faengt den Fehler ab statt die App zu crashen.
 */
export function safeSubscribe(
  channel: ReturnType<typeof supabase.channel>
): ReturnType<typeof supabase.channel> {
  try {
    return channel.subscribe((status, err) => {
      if (err) {
        console.warn('[Realtime] Subscription error (non-fatal):', err.message);
      }
    });
  } catch (e) {
    console.warn('[Realtime] WebSocket not available (non-fatal):', e);
    return channel;
  }
}